spring:
  rabbitmq:
    host: 10.211.55.19 # 主机名
    port: 5672 # 端口
    virtual-host: my_vhost # 虚拟主机
    username: admin # 用户名
    password: admin # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息