spring:
  datasource:
    druid:
      url: jdbc:mysql://10.211.55.19:3306/resource?serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver

minio:
  url: xxxx
  username: xxxx
  password: xxxx

resource:
  path:
    avatar-bucket: avatar
    image-bucket: image
    image-url-base: http://image.scblogs.cn/

qiniu:
  access-key: xxxx
  secret-key: xxxx
  prefix-url: xxxx
